
// AUTOGENERATED!!! Do not modify! Your changes will be lost after .tt template regenerates.
// Modify the .tt template instead!


using System;
using System.Collections.Generic;
using System.Text;
using System.Text.Json.Serialization;
using System.Runtime.InteropServices;

namespace ResoniteLink
{
    
            // The struct layout is not necessary for serialization itself, but this simplifies the use
            // of these types within FrooxEngine itself
            [StructLayout(LayoutKind.Sequential)]
            public struct float2x2
            {
                                        [JsonPropertyName("m00")]
                        public float m00 { get; set; }
                                                [JsonPropertyName("m01")]
                        public float m01 { get; set; }
                                                [JsonPropertyName("m10")]
                        public float m10 { get; set; }
                                                [JsonPropertyName("m11")]
                        public float m11 { get; set; }
                                    }

            
            // The struct layout is not necessary for serialization itself, but this simplifies the use
            // of these types within FrooxEngine itself
            [StructLayout(LayoutKind.Sequential)]
            public struct float3x3
            {
                                        [JsonPropertyName("m00")]
                        public float m00 { get; set; }
                                                [JsonPropertyName("m01")]
                        public float m01 { get; set; }
                                                [JsonPropertyName("m02")]
                        public float m02 { get; set; }
                                                [JsonPropertyName("m10")]
                        public float m10 { get; set; }
                                                [JsonPropertyName("m11")]
                        public float m11 { get; set; }
                                                [JsonPropertyName("m12")]
                        public float m12 { get; set; }
                                                [JsonPropertyName("m20")]
                        public float m20 { get; set; }
                                                [JsonPropertyName("m21")]
                        public float m21 { get; set; }
                                                [JsonPropertyName("m22")]
                        public float m22 { get; set; }
                                    }

            
            // The struct layout is not necessary for serialization itself, but this simplifies the use
            // of these types within FrooxEngine itself
            [StructLayout(LayoutKind.Sequential)]
            public struct float4x4
            {
                                        [JsonPropertyName("m00")]
                        public float m00 { get; set; }
                                                [JsonPropertyName("m01")]
                        public float m01 { get; set; }
                                                [JsonPropertyName("m02")]
                        public float m02 { get; set; }
                                                [JsonPropertyName("m03")]
                        public float m03 { get; set; }
                                                [JsonPropertyName("m10")]
                        public float m10 { get; set; }
                                                [JsonPropertyName("m11")]
                        public float m11 { get; set; }
                                                [JsonPropertyName("m12")]
                        public float m12 { get; set; }
                                                [JsonPropertyName("m13")]
                        public float m13 { get; set; }
                                                [JsonPropertyName("m20")]
                        public float m20 { get; set; }
                                                [JsonPropertyName("m21")]
                        public float m21 { get; set; }
                                                [JsonPropertyName("m22")]
                        public float m22 { get; set; }
                                                [JsonPropertyName("m23")]
                        public float m23 { get; set; }
                                                [JsonPropertyName("m30")]
                        public float m30 { get; set; }
                                                [JsonPropertyName("m31")]
                        public float m31 { get; set; }
                                                [JsonPropertyName("m32")]
                        public float m32 { get; set; }
                                                [JsonPropertyName("m33")]
                        public float m33 { get; set; }
                                    }

            
            // The struct layout is not necessary for serialization itself, but this simplifies the use
            // of these types within FrooxEngine itself
            [StructLayout(LayoutKind.Sequential)]
            public struct double2x2
            {
                                        [JsonPropertyName("m00")]
                        public double m00 { get; set; }
                                                [JsonPropertyName("m01")]
                        public double m01 { get; set; }
                                                [JsonPropertyName("m10")]
                        public double m10 { get; set; }
                                                [JsonPropertyName("m11")]
                        public double m11 { get; set; }
                                    }

            
            // The struct layout is not necessary for serialization itself, but this simplifies the use
            // of these types within FrooxEngine itself
            [StructLayout(LayoutKind.Sequential)]
            public struct double3x3
            {
                                        [JsonPropertyName("m00")]
                        public double m00 { get; set; }
                                                [JsonPropertyName("m01")]
                        public double m01 { get; set; }
                                                [JsonPropertyName("m02")]
                        public double m02 { get; set; }
                                                [JsonPropertyName("m10")]
                        public double m10 { get; set; }
                                                [JsonPropertyName("m11")]
                        public double m11 { get; set; }
                                                [JsonPropertyName("m12")]
                        public double m12 { get; set; }
                                                [JsonPropertyName("m20")]
                        public double m20 { get; set; }
                                                [JsonPropertyName("m21")]
                        public double m21 { get; set; }
                                                [JsonPropertyName("m22")]
                        public double m22 { get; set; }
                                    }

            
            // The struct layout is not necessary for serialization itself, but this simplifies the use
            // of these types within FrooxEngine itself
            [StructLayout(LayoutKind.Sequential)]
            public struct double4x4
            {
                                        [JsonPropertyName("m00")]
                        public double m00 { get; set; }
                                                [JsonPropertyName("m01")]
                        public double m01 { get; set; }
                                                [JsonPropertyName("m02")]
                        public double m02 { get; set; }
                                                [JsonPropertyName("m03")]
                        public double m03 { get; set; }
                                                [JsonPropertyName("m10")]
                        public double m10 { get; set; }
                                                [JsonPropertyName("m11")]
                        public double m11 { get; set; }
                                                [JsonPropertyName("m12")]
                        public double m12 { get; set; }
                                                [JsonPropertyName("m13")]
                        public double m13 { get; set; }
                                                [JsonPropertyName("m20")]
                        public double m20 { get; set; }
                                                [JsonPropertyName("m21")]
                        public double m21 { get; set; }
                                                [JsonPropertyName("m22")]
                        public double m22 { get; set; }
                                                [JsonPropertyName("m23")]
                        public double m23 { get; set; }
                                                [JsonPropertyName("m30")]
                        public double m30 { get; set; }
                                                [JsonPropertyName("m31")]
                        public double m31 { get; set; }
                                                [JsonPropertyName("m32")]
                        public double m32 { get; set; }
                                                [JsonPropertyName("m33")]
                        public double m33 { get; set; }
                                    }

            }
