
// AUTOGENERATED!!! Do not modify! Your changes will be lost after .tt template regenerates.
// Modify the .tt template instead!


using System;
using System.Collections.Generic;
using System.Text;
using System.Text.Json.Serialization;
using System.Runtime.InteropServices;


namespace ResoniteLink
{
    
        // The struct layout is not necessary for serialization itself, but this simplifies the use
        // of these types within FrooxEngine itself
        [StructLayout(LayoutKind.Sequential)]
        public struct floatQ
        {
                            [JsonPropertyName("x")]
                public float x { get; set; }
                                [JsonPropertyName("y")]
                public float y { get; set; }
                                [JsonPropertyName("z")]
                public float z { get; set; }
                                [JsonPropertyName("w")]
                public float w { get; set; }
                        }
        
        // The struct layout is not necessary for serialization itself, but this simplifies the use
        // of these types within FrooxEngine itself
        [StructLayout(LayoutKind.Sequential)]
        public struct doubleQ
        {
                            [JsonPropertyName("x")]
                public double x { get; set; }
                                [JsonPropertyName("y")]
                public double y { get; set; }
                                [JsonPropertyName("z")]
                public double z { get; set; }
                                [JsonPropertyName("w")]
                public double w { get; set; }
                        }
        }
