
// AUTOGENERATED!!! Do not modify! Your changes will be lost after .tt template regenerates.
// Modify the .tt template instead!


using System;
using System.Collections.Generic;
using System.Text;
using System.Text.Json.Serialization;
using System.Runtime.InteropServices;


namespace ResoniteLink
{
    
            // The struct layout is not necessary for serialization itself, but this simplifies the use
            // of these types within FrooxEngine itself
            [StructLayout(LayoutKind.Sequential)]
            public struct float2
            {
                                    [JsonPropertyName("x")]
                    public float x { get; set; }
                                        [JsonPropertyName("y")]
                    public float y { get; set; }
                                }
            
            // The struct layout is not necessary for serialization itself, but this simplifies the use
            // of these types within FrooxEngine itself
            [StructLayout(LayoutKind.Sequential)]
            public struct float3
            {
                                    [JsonPropertyName("x")]
                    public float x { get; set; }
                                        [JsonPropertyName("y")]
                    public float y { get; set; }
                                        [JsonPropertyName("z")]
                    public float z { get; set; }
                                }
            
            // The struct layout is not necessary for serialization itself, but this simplifies the use
            // of these types within FrooxEngine itself
            [StructLayout(LayoutKind.Sequential)]
            public struct float4
            {
                                    [JsonPropertyName("x")]
                    public float x { get; set; }
                                        [JsonPropertyName("y")]
                    public float y { get; set; }
                                        [JsonPropertyName("z")]
                    public float z { get; set; }
                                        [JsonPropertyName("w")]
                    public float w { get; set; }
                                }
            
            // The struct layout is not necessary for serialization itself, but this simplifies the use
            // of these types within FrooxEngine itself
            [StructLayout(LayoutKind.Sequential)]
            public struct double2
            {
                                    [JsonPropertyName("x")]
                    public double x { get; set; }
                                        [JsonPropertyName("y")]
                    public double y { get; set; }
                                }
            
            // The struct layout is not necessary for serialization itself, but this simplifies the use
            // of these types within FrooxEngine itself
            [StructLayout(LayoutKind.Sequential)]
            public struct double3
            {
                                    [JsonPropertyName("x")]
                    public double x { get; set; }
                                        [JsonPropertyName("y")]
                    public double y { get; set; }
                                        [JsonPropertyName("z")]
                    public double z { get; set; }
                                }
            
            // The struct layout is not necessary for serialization itself, but this simplifies the use
            // of these types within FrooxEngine itself
            [StructLayout(LayoutKind.Sequential)]
            public struct double4
            {
                                    [JsonPropertyName("x")]
                    public double x { get; set; }
                                        [JsonPropertyName("y")]
                    public double y { get; set; }
                                        [JsonPropertyName("z")]
                    public double z { get; set; }
                                        [JsonPropertyName("w")]
                    public double w { get; set; }
                                }
            
            // The struct layout is not necessary for serialization itself, but this simplifies the use
            // of these types within FrooxEngine itself
            [StructLayout(LayoutKind.Sequential)]
            public struct byte2
            {
                                    [JsonPropertyName("x")]
                    public byte x { get; set; }
                                        [JsonPropertyName("y")]
                    public byte y { get; set; }
                                }
            
            // The struct layout is not necessary for serialization itself, but this simplifies the use
            // of these types within FrooxEngine itself
            [StructLayout(LayoutKind.Sequential)]
            public struct byte3
            {
                                    [JsonPropertyName("x")]
                    public byte x { get; set; }
                                        [JsonPropertyName("y")]
                    public byte y { get; set; }
                                        [JsonPropertyName("z")]
                    public byte z { get; set; }
                                }
            
            // The struct layout is not necessary for serialization itself, but this simplifies the use
            // of these types within FrooxEngine itself
            [StructLayout(LayoutKind.Sequential)]
            public struct byte4
            {
                                    [JsonPropertyName("x")]
                    public byte x { get; set; }
                                        [JsonPropertyName("y")]
                    public byte y { get; set; }
                                        [JsonPropertyName("z")]
                    public byte z { get; set; }
                                        [JsonPropertyName("w")]
                    public byte w { get; set; }
                                }
            
            // The struct layout is not necessary for serialization itself, but this simplifies the use
            // of these types within FrooxEngine itself
            [StructLayout(LayoutKind.Sequential)]
            public struct ushort2
            {
                                    [JsonPropertyName("x")]
                    public ushort x { get; set; }
                                        [JsonPropertyName("y")]
                    public ushort y { get; set; }
                                }
            
            // The struct layout is not necessary for serialization itself, but this simplifies the use
            // of these types within FrooxEngine itself
            [StructLayout(LayoutKind.Sequential)]
            public struct ushort3
            {
                                    [JsonPropertyName("x")]
                    public ushort x { get; set; }
                                        [JsonPropertyName("y")]
                    public ushort y { get; set; }
                                        [JsonPropertyName("z")]
                    public ushort z { get; set; }
                                }
            
            // The struct layout is not necessary for serialization itself, but this simplifies the use
            // of these types within FrooxEngine itself
            [StructLayout(LayoutKind.Sequential)]
            public struct ushort4
            {
                                    [JsonPropertyName("x")]
                    public ushort x { get; set; }
                                        [JsonPropertyName("y")]
                    public ushort y { get; set; }
                                        [JsonPropertyName("z")]
                    public ushort z { get; set; }
                                        [JsonPropertyName("w")]
                    public ushort w { get; set; }
                                }
            
            // The struct layout is not necessary for serialization itself, but this simplifies the use
            // of these types within FrooxEngine itself
            [StructLayout(LayoutKind.Sequential)]
            public struct uint2
            {
                                    [JsonPropertyName("x")]
                    public uint x { get; set; }
                                        [JsonPropertyName("y")]
                    public uint y { get; set; }
                                }
            
            // The struct layout is not necessary for serialization itself, but this simplifies the use
            // of these types within FrooxEngine itself
            [StructLayout(LayoutKind.Sequential)]
            public struct uint3
            {
                                    [JsonPropertyName("x")]
                    public uint x { get; set; }
                                        [JsonPropertyName("y")]
                    public uint y { get; set; }
                                        [JsonPropertyName("z")]
                    public uint z { get; set; }
                                }
            
            // The struct layout is not necessary for serialization itself, but this simplifies the use
            // of these types within FrooxEngine itself
            [StructLayout(LayoutKind.Sequential)]
            public struct uint4
            {
                                    [JsonPropertyName("x")]
                    public uint x { get; set; }
                                        [JsonPropertyName("y")]
                    public uint y { get; set; }
                                        [JsonPropertyName("z")]
                    public uint z { get; set; }
                                        [JsonPropertyName("w")]
                    public uint w { get; set; }
                                }
            
            // The struct layout is not necessary for serialization itself, but this simplifies the use
            // of these types within FrooxEngine itself
            [StructLayout(LayoutKind.Sequential)]
            public struct ulong2
            {
                                    [JsonPropertyName("x")]
                    public ulong x { get; set; }
                                        [JsonPropertyName("y")]
                    public ulong y { get; set; }
                                }
            
            // The struct layout is not necessary for serialization itself, but this simplifies the use
            // of these types within FrooxEngine itself
            [StructLayout(LayoutKind.Sequential)]
            public struct ulong3
            {
                                    [JsonPropertyName("x")]
                    public ulong x { get; set; }
                                        [JsonPropertyName("y")]
                    public ulong y { get; set; }
                                        [JsonPropertyName("z")]
                    public ulong z { get; set; }
                                }
            
            // The struct layout is not necessary for serialization itself, but this simplifies the use
            // of these types within FrooxEngine itself
            [StructLayout(LayoutKind.Sequential)]
            public struct ulong4
            {
                                    [JsonPropertyName("x")]
                    public ulong x { get; set; }
                                        [JsonPropertyName("y")]
                    public ulong y { get; set; }
                                        [JsonPropertyName("z")]
                    public ulong z { get; set; }
                                        [JsonPropertyName("w")]
                    public ulong w { get; set; }
                                }
            
            // The struct layout is not necessary for serialization itself, but this simplifies the use
            // of these types within FrooxEngine itself
            [StructLayout(LayoutKind.Sequential)]
            public struct sbyte2
            {
                                    [JsonPropertyName("x")]
                    public sbyte x { get; set; }
                                        [JsonPropertyName("y")]
                    public sbyte y { get; set; }
                                }
            
            // The struct layout is not necessary for serialization itself, but this simplifies the use
            // of these types within FrooxEngine itself
            [StructLayout(LayoutKind.Sequential)]
            public struct sbyte3
            {
                                    [JsonPropertyName("x")]
                    public sbyte x { get; set; }
                                        [JsonPropertyName("y")]
                    public sbyte y { get; set; }
                                        [JsonPropertyName("z")]
                    public sbyte z { get; set; }
                                }
            
            // The struct layout is not necessary for serialization itself, but this simplifies the use
            // of these types within FrooxEngine itself
            [StructLayout(LayoutKind.Sequential)]
            public struct sbyte4
            {
                                    [JsonPropertyName("x")]
                    public sbyte x { get; set; }
                                        [JsonPropertyName("y")]
                    public sbyte y { get; set; }
                                        [JsonPropertyName("z")]
                    public sbyte z { get; set; }
                                        [JsonPropertyName("w")]
                    public sbyte w { get; set; }
                                }
            
            // The struct layout is not necessary for serialization itself, but this simplifies the use
            // of these types within FrooxEngine itself
            [StructLayout(LayoutKind.Sequential)]
            public struct short2
            {
                                    [JsonPropertyName("x")]
                    public short x { get; set; }
                                        [JsonPropertyName("y")]
                    public short y { get; set; }
                                }
            
            // The struct layout is not necessary for serialization itself, but this simplifies the use
            // of these types within FrooxEngine itself
            [StructLayout(LayoutKind.Sequential)]
            public struct short3
            {
                                    [JsonPropertyName("x")]
                    public short x { get; set; }
                                        [JsonPropertyName("y")]
                    public short y { get; set; }
                                        [JsonPropertyName("z")]
                    public short z { get; set; }
                                }
            
            // The struct layout is not necessary for serialization itself, but this simplifies the use
            // of these types within FrooxEngine itself
            [StructLayout(LayoutKind.Sequential)]
            public struct short4
            {
                                    [JsonPropertyName("x")]
                    public short x { get; set; }
                                        [JsonPropertyName("y")]
                    public short y { get; set; }
                                        [JsonPropertyName("z")]
                    public short z { get; set; }
                                        [JsonPropertyName("w")]
                    public short w { get; set; }
                                }
            
            // The struct layout is not necessary for serialization itself, but this simplifies the use
            // of these types within FrooxEngine itself
            [StructLayout(LayoutKind.Sequential)]
            public struct int2
            {
                                    [JsonPropertyName("x")]
                    public int x { get; set; }
                                        [JsonPropertyName("y")]
                    public int y { get; set; }
                                }
            
            // The struct layout is not necessary for serialization itself, but this simplifies the use
            // of these types within FrooxEngine itself
            [StructLayout(LayoutKind.Sequential)]
            public struct int3
            {
                                    [JsonPropertyName("x")]
                    public int x { get; set; }
                                        [JsonPropertyName("y")]
                    public int y { get; set; }
                                        [JsonPropertyName("z")]
                    public int z { get; set; }
                                }
            
            // The struct layout is not necessary for serialization itself, but this simplifies the use
            // of these types within FrooxEngine itself
            [StructLayout(LayoutKind.Sequential)]
            public struct int4
            {
                                    [JsonPropertyName("x")]
                    public int x { get; set; }
                                        [JsonPropertyName("y")]
                    public int y { get; set; }
                                        [JsonPropertyName("z")]
                    public int z { get; set; }
                                        [JsonPropertyName("w")]
                    public int w { get; set; }
                                }
            
            // The struct layout is not necessary for serialization itself, but this simplifies the use
            // of these types within FrooxEngine itself
            [StructLayout(LayoutKind.Sequential)]
            public struct long2
            {
                                    [JsonPropertyName("x")]
                    public long x { get; set; }
                                        [JsonPropertyName("y")]
                    public long y { get; set; }
                                }
            
            // The struct layout is not necessary for serialization itself, but this simplifies the use
            // of these types within FrooxEngine itself
            [StructLayout(LayoutKind.Sequential)]
            public struct long3
            {
                                    [JsonPropertyName("x")]
                    public long x { get; set; }
                                        [JsonPropertyName("y")]
                    public long y { get; set; }
                                        [JsonPropertyName("z")]
                    public long z { get; set; }
                                }
            
            // The struct layout is not necessary for serialization itself, but this simplifies the use
            // of these types within FrooxEngine itself
            [StructLayout(LayoutKind.Sequential)]
            public struct long4
            {
                                    [JsonPropertyName("x")]
                    public long x { get; set; }
                                        [JsonPropertyName("y")]
                    public long y { get; set; }
                                        [JsonPropertyName("z")]
                    public long z { get; set; }
                                        [JsonPropertyName("w")]
                    public long w { get; set; }
                                }
            
            // The struct layout is not necessary for serialization itself, but this simplifies the use
            // of these types within FrooxEngine itself
            [StructLayout(LayoutKind.Sequential)]
            public struct bool2
            {
                                    [JsonPropertyName("x")]
                    public bool x { get; set; }
                                        [JsonPropertyName("y")]
                    public bool y { get; set; }
                                }
            
            // The struct layout is not necessary for serialization itself, but this simplifies the use
            // of these types within FrooxEngine itself
            [StructLayout(LayoutKind.Sequential)]
            public struct bool3
            {
                                    [JsonPropertyName("x")]
                    public bool x { get; set; }
                                        [JsonPropertyName("y")]
                    public bool y { get; set; }
                                        [JsonPropertyName("z")]
                    public bool z { get; set; }
                                }
            
            // The struct layout is not necessary for serialization itself, but this simplifies the use
            // of these types within FrooxEngine itself
            [StructLayout(LayoutKind.Sequential)]
            public struct bool4
            {
                                    [JsonPropertyName("x")]
                    public bool x { get; set; }
                                        [JsonPropertyName("y")]
                    public bool y { get; set; }
                                        [JsonPropertyName("z")]
                    public bool z { get; set; }
                                        [JsonPropertyName("w")]
                    public bool w { get; set; }
                                }
            }
